# 3. Deploy a MySQL Database
# Create a Secret for the MySQL root password
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: fullstack-app
type: Opaque
data:
  mysql-root-password: cGFzc3dvcmQ= # Base64 encoded 'password' 

# kubectl apply -f C_mysql-secret.yaml