# 6. Configure Services
# Create a ClusterIP service for the MySQL database
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: fullstack-app
spec:
  type: ClusterIP
  ports:
  - port: 3306
  selector:
    app: mysql

# kubectl apply -f H_mysql-service.yaml