# Create a ClusterIP service for the backend server
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: fullstack-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: backend

    