# Create a NodePort service for the frontend server
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: fullstack-app
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
  selector:
    app: frontend

# kubectl apply -f J_frontend-service.yaml