# 8. Use Secrets for Sensitive Data
# Create a Secret for storing API keys used by the backend server
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: fullstack-app
type: Opaque
data:
  api-key: YXBpLWtleQ== # Base64 encoded 'api-key'

#kubectl apply -f M_backend-secret.yaml


# kubectl get all -n fullstack-app
# minikube ip
# curl http://<minikube-ip>:30001
# kubectl get pods -n fullstack-app