# Configure Services
# Create services to expose the applications.
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: multi-tier-app
spec:
  type: ClusterIP
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    app: redis

#kubectl apply -f G_redis-service.yaml