apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: multi-tier-app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app: backend
  
# H_backend-service.yaml