apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: multi-tier-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30002
  selector:
    app: frontend


