# Use Secrets for Sensitive Data
# Create a Secret for storing sensitive information used by the backend server.
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: multi-tier-app
type: Opaque
data:
  db-password: dGVzdHBhc3N3b3Jk  # base64 encoded 'testpassword'


# L_backend-secret.yaml





# --------------
# Get Minikube IP -- > minikube ip
# Check the Frontend Service -- > curl http://192.168.49.2:30002
# Access the Backend Service from the Frontend Pod
# kubectl get pods -n multi-tier-app
# kubectl exec -it backenf-multitier-pod -n multi-tier-app -- curl http://redis:6379

# go to fron end - curl http://192.168.49.2:30002


# Access the Backend Service from the Frontend Pod
# kubectl exec -it frontend-multitier-pod -n multi-tier-app -- curl http://backend:8080


