# Set Up RBAC Permissions
# Create a Role and RoleBinding to manage permissions within the namespace.
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: secure-app
  name: pod-manager
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["get", "list", "watch", "create", "delete"]

# kubectl apply -f C_role.yaml