# Deploy a MongoDB Database
# Create a Secret for the MongoDB credentials and a ConfigMap for database configuration.
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: secure-app
type: Opaque
data:
  mongo-root-username: cm9uZW4= #ronen
  mongo-root-password: cm9uZW5i #ronenb

# kubectl apply -f E_mongodb-secret.yaml  