# Configure Services
#  Create a ClusterIP service for the MongoDB database
# Create a ClusterIP service for the MongoDB database.
# Create a ClusterIP service for the backend server.
# Create a NodePort service for the frontend server.
# Create an ExternalName service to map an external DNS name.

apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: secure-app
spec:
  type: ClusterIP
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: mongodb

# kubectl apply -f J_mongodb-service.yaml