apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: secure-app
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: backend

# kubectl apply -f K_backend-service.yaml