apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: secure-app
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30003
  selector:
    app: frontend

# kubectl apply -f L_frontend-service.yaml