# Use Secrets for Sensitive Data
# Create a Secret for storing API keys used by the backend server.
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: secure-app
type: Opaque
data:
  api-key: cm9uZW5i # ronenb

#  kubectl apply -f O_backend-secret.yaml


# minikube ip
# curl http://192.168.49.2:30001
# Find the name of a frontend pod.  kubectl get pods -n secure-app -l app=frontend
# Access the backend service from within the frontend pod 
# kubectl get pods -n secure-app -l app=frontend