# 4.7 Deploy the Flask application and expose it as a service.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask
  namespace: lesson-three-proj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: ronben2311/flask-app:latest  # Corrected image name to match Docker Hub repository
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: lesson-three-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: lesson-three-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: lesson-three-secret
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: lesson-three-secret
              key: DB_PASSWORD
        - name: REDIS_HOST
          value: "yourredisservice"  # Adjust if necessary
        - name: REDIS_PORT
          value: "6379"
