# 5.1. Horizontal Pod Autoscaler (HPA)
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: flask-hpa
  namespace: lesson-three-proj
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flask
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50