# 4.4  Define PersistentVolume and PersistentVolumeClaim for PostgreSQL data storage.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: lesson-three-proj
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: lesson-three-proj
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi